export const ImageSet = {
  brandDark: '/assets/images/brand-dark.svg',
  brandLight: '/assets/images/brand-light.svg',
  favicon: '/assets/images/favicon.ico',
  homeJumbotron: '/assets/images/jumbotron-image.svg',
  serviceOperations: '/assets/images/service-operations.svg',
  serviceBadge: '/assets/images/service-badge.svg',
  serviceClipboard: '/assets/images/service-clipboard.svg',
  servicePlan: '/assets/images/service-plan.svg',
  serviceInnovation: '/assets/images/service-innovation.svg',
  serviceProfile: '/assets/images/service-profile.svg',
  contactEmail: '/assets/images/contact-email.svg',
  contactPhone: '/assets/images/contact-phone.svg',
  contactFB: '/assets/images/contact-fb.svg',
  contactWeb: '/assets/images/contact-web.svg',
  lawAboutBG: '/assets/images/law-about-bg.png',
  lawContactBG: '/assets/images/law-contact-bg.png',
  homeClientOne: '/assets/images/client-1.png',
  homeClientTwo: '/assets/images/client-2.png',
  homeClientThree: '/assets/images/client-3.png',
  homeStarGrey: '/assets/images/star-grey.svg',
  homeStarGolden: '/assets/images/star-golden.svg',
};

export type ImageKey = keyof typeof ImageSet;
